version: '3'
services:
  toposoid-knowledge-register-web:
    image: toposoid-knowledge-register-web:0.6-SNAPSHOT
    tty: true
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-knowledge-register-web
      - TOPOSOID_GRAPHDB_HOST=neo4j
      - TOPOSOID_GRAPHDB_WEB_HOST=scala-data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_WEB_PORT=9005
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_HOST=toposoid-sentence-parser-japanese-web
      - TOPOSOID_SENTENCE_PARSER_JP_WEB_PORT=9001
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_HOST=toposoid-sentence-parser-english-web
      - TOPOSOID_SENTENCE_PARSER_EN_WEB_PORT=9007
      - TOPOSOID_COMMON_NLP_JP_WEB_HOST=toposoid-common-nlp-japanese-web
      - TOPOSOID_COMMON_NLP_JP_WEB_PORT=9006
      - TOPOSOID_COMMON_NLP_EN_WEB_HOST=toposoid-common-nlp-english-web
      - TOPOSOID_COMMON_NLP_EN_WEB_PORT=9008
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_HOST=data-accessor-sentence-weaviate-web
      - TOPOSOID_SENTENCE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_HOST=data-accessor-image-weaviate-web
      - TOPOSOID_IMAGE_VECTORDB_ACCESSOR_PORT=9011
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_HOST=toposoid-common-image-recognition-web
      - TOPOSOID_COMMON_IMAGE_RECOGNITION_PORT=9013
      - TOPOSOID_CONTENTS_ADMIN_HOST=toposoid-contents-admin-web
      - TOPOSOID_CONTENTS_ADMIN_PORT=9012
      - PLAY_HTTP_PORT=9002
  toposoid-sentence-parser-japanese-web:
    image: toposoid/toposoid-sentence-parser-japanese-web:0.6-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sentence-parser-japanese-web
      - PLAY_HTTP_PORT=9001
    ports:
      - 9001:9001
  toposoid-common-nlp-japanese-web:
    image: toposoid/toposoid-common-nlp-japanese-web:0.6-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-common-nlp-japanese-web
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_JP=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_JP=0.68
      - TOPOSOID_CHIVE_MODEL_VERSION=chive-1.2-mc15.kv
      - TOPOSOID_SENTENCEBERT_MODEL_JP=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9006
    ports:
      - 9006:9006
  toposoid-sentence-parser-english-web:
    image: toposoid/toposoid-sentence-parser-english-web:0.6-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-sentence-parser-english-web
      - PLAY_HTTP_PORT=9007
      - TOPOSOID_CORENLP_HOST=corenlp
      - TOPOSOID_PARSER_SPACY_MODEL_EN=en_core_web_lg
    ports:
      - 9007:9007
  toposoid-common-nlp-english-web:
    image: toposoid/toposoid-common-nlp-english-web:0.6-SNAPSHOT
    environment:
      - PRIVATE_IP_ADDRESS=toposoid-common-nlp-english-web
      - TOPOSOID_SYNONYM_NOUN_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_SYNONYM_VERB_SIMILARITY_THRESHHOLD_EN=0.52
      - TOPOSOID_WORD2VEC_SIMILARITY_THRESHHOLD_EN=0.78
      - TOPOSOID_SPACY_MODEL_EN=en_core_web_lg
      - TOPOSOID_SENTENCEBERT_MODEL_EN=sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      - TOPOSOID_SENTENCE_TRANSFORMERS_HOME=./models
      - PLAY_HTTP_PORT=9008
    ports:
      - 9008:9008
  corenlp:
    image: toposoid/corenlp:3.4.2
    ports:
      - 9000:9000
  neo4j:
    image: neo4j:4.4.23
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_transaction_timeout=10s
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/p@ssw0rd
  toposoid-contents-admin-web:
    image: toposoid/toposoid-contents-admin-web:0.6-SNAPSHOT
    environment:
      - TOPOSOID_CONTENTS_URL=http://toposoid-contents-admin-web:9012/contents/
    ports:
      - 9012:9012

  toposoid-common-image-recognition-web:
    image: toposoid/toposoid-common-image-recognition-web:0.6-SNAPSHOT
    environment:
      - TOPOSOID_IMAGE_RECOGNITION_VIT_MODEL=google/vit-base-patch16-224
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_MODEL=apple/mobilevit-small
      - TOPOSOID_IMAGE_RECOGNITION_MOBILE_VIT_USE=0      -
    ports:
      - 9013:9013

  data-accessor-sentence-weaviate-web:
    image: toposoid/data-accessor-weaviate-web:0.6-SNAPSHOT
    environment:
      - TOPOSOID_WEAVIATE_HOST=sentence-weaviate
      - TOPOSOID_WEAVIATE_PORT=8080
      - TOPOSOID_WEAVIATE_SIMILARITY_THRESHOLD=0.85
      - TOPOSOID_DATA_ACCESSOR_PORT=9011
    ports:
      - 9020:9011
    depends_on:
      - sentence-weaviate
  sentence-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.2
    ports:
      - 8080:8080
    #volumes:
    #  - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      HUGGINGFACE_APIKEY: ''
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

  data-accessor-image-weaviate-web:
    image: toposoid/data-accessor-weaviate-web:0.6-SNAPSHOT
    environment:
      - TOPOSOID_WEAVIATE_HOST=image-weaviate
      - TOPOSOID_WEAVIATE_PORT=8081
      - TOPOSOID_WEAVIATE_SIMILARITY_THRESHOLD=0.85
      - TOPOSOID_DATA_ACCESSOR_PORT=9011
    ports:
      - 9021:9011
    depends_on:
      - image-weaviate

  image-weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8081'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.21.2
    ports:
      - 8081:8081
    #volumes:
    #  - /var/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-huggingface'
      HUGGINGFACE_APIKEY: ''
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

  scala-data-accessor-neo4j-web:
    image: toposoid/scala-data-accessor-neo4j-web:0.6-SNAPSHOT-lowspec
    environment:
      - PRIVATE_IP_ADDRESS=scala-data-accessor-neo4j-web
      - TOPOSOID_GRAPHDB_HOST=neo4j
      - PLAY_HTTP_PORT=9005
    ports:
      - 9005:9005
