FROM toposoid/toposoid-scala-lib:0.4

WORKDIR /app
ARG TARGET_BRANCH
ENV DEPLOYMENT=local
ENV _JAVA_OPTIONS="-Xms512m -Xmx1g"

RUN git clone https://github.com/toposoid/toposoid-knowledge-register-web.git \
&& cd toposoid-knowledge-register-web \
&& git fetch origin ${TARGET_BRANCH} \
&& git checkout ${TARGET_BRANCH}
