version: '3'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

services:
  toposoid-knowledge-register-web:
    image: toposoid/toposoid-knowledge-register-web:0.1-SNAPSHOT
    environment:
      - GRAPHDB_HOST=172.30.0.2
      - PRIVATE_IP_ADDRESS=localhost
      - PLAY_HTTP_PORT=9002
    ports:
      - 9002:9002
    networks:
      app_net:
        ipv4_address: 172.30.0.3
  neo4j:
    image: neo4j:4.1.3
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_AUTH=neo4j/p@ssw0rd
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      app_net:
        ipv4_address: 172.30.0.2
