name: Test And Build
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
env:
  PJ_ACTOR: toposoid
  PJ_REPO: toposoid-knowledge-register-web
  PJ_BRANCH: main
  PJ_VERSION: 0.4
jobs:
  unit-test_toposoid-knowledge-register-web:
    runs-on: self-hosted
    steps:
      - name: Clone ${{ env.PJ_REPO }}
        uses: actions/checkout@v3
        with:
            repository: ${{ env.PJ_ACTOR }}/${{ env.PJ_REPO }}
      - name: Execute tests
        run: |
            cd ${GITHUB_WORKSPACE} && cd ../
            cd ./${{ env.PJ_REPO }}
            rm -f vald-config/backup/*
            echo "$(id -u $USER):$(id -g $USER)"
            docker rm --force $(docker ps -a -q) > /dev/null 2>&1 && :
            docker rmi --force $(docker images -q) > /dev/null 2>&1 && :
            docker images
            docker system prune -f
            docker volume prune -f
            docker build --build-arg TARGET_BRANCH=${{ env.PJ_BRANCH }} --tag ${{ env.PJ_REPO }}:${{ env.PJ_VERSION }} -f Dockerfile-workflow .
            docker-compose -f docker-compose-workflow.yml up -d toposoid-knowledge-register-web
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt test:headerCheck"
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt compile"
            docker-compose -f docker-compose-workflow.yml up -d neo4j
            docker-compose -f docker-compose-workflow.yml up -d vald
            docker-compose -f docker-compose-workflow.yml up -d data-accessor-vald-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-japanese-web
            curl -X POST http://localhost:7474
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*Japanese'"
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-common-nlp-japanese-web
            docker-compose -f docker-compose-workflow.yml rm -fsv toposoid-sentence-parser-japanese-web
            docker rmi --force toposoid/toposoid-sentence-parser-japanese-web:${{ env.PJ_VERSION }}-workflow
            docker rmi --force toposoid/toposoid-common-nlp-japanese-web:${{ env.PJ_VERSION }}-workflow
            docker-compose -f docker-compose-workflow.yml rm -fsv vald
            rm -f vald-config/backup/*
            docker-compose -f docker-compose-workflow.yml up -d vald
            docker images
            docker system prune -f
            docker volume prune -f
            docker-compose -f docker-compose-workflow.yml up -d corenlp
            docker-compose -f docker-compose-workflow.yml up -d toposoid-common-nlp-english-web
            docker-compose -f docker-compose-workflow.yml up -d toposoid-sentence-parser-english-web
            docker-compose -f docker-compose-workflow.yml exec -T ${{ env.PJ_REPO }} bash -c "cd ${{ env.PJ_REPO }} && sbt 'testOnly **.*English'"
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3
        with:
          images: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build And Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
      - name: Build And Push Docker Image For Test
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-smallspec
          push: true
          tags: toposoid/${{ env.PJ_REPO }}:${{ env.PJ_VERSION }}-workflow
          build-args: |
            TARGET_BRANCH=${{ env.PJ_BRANCH }}
